### ISSUE TITLE
184 Version app details

### ISSUE THREAD

**Issue by kingbotss** [itsMoji/Instagram_SSL_Pinning#101]
x-ig-app-locale: | en_US
x-ig-device-locale: | en_US
x-ig-mapped-locale: | en_US
x-bloks-version-id: | **befa8522d3a650f9592e33e4540d527c5b93babbdd6233a1bd40e955c9567f30**
x-ig-capabilities: | **3brTvx0=**
x-ig-app-id: | **567067343352427**
user-agent: | **Instagram 184.0.0.30.117** Android (25/7.1.2; 240dpi; 720x1280; samsung; SM-G935; SM-G935; intel; en_US; **285855788**)
accept-language: | en-US
ig-intended-user-id: | 0
content-type: | application/x-www-form-urlencoded; charset=UTF-8
accept-encoding: | zstd, gzip, deflate
x-fb-http-engine: | Liger
x-fb-client-ip: | True
x-fb-server-cluster: | True
singature: SIGNATURE.

Text copied from MITMPROXY
This is info is for information purpose only...

**Comment by bolds07** [comment]
Is Instagram official app using http 1.1 or http2?

I'm using burp and since last update seems that it forces api to go http2 and at same time it rewrites all http headers to be `First-Letter-Capital`

This is an absurd error since http2 specification says that all headers should be lowercase.

Then i tried to use mitmproxy but it didnt work well and the connection went http 1.1

i tried fiddler and charles but they didnt work, can annoyone help me to confirm what http version is instagram officially using?
are the response headers named all lowercase or it kept that pattern like:
```
X-IG-WWW-Claim
X-MID
```

can anyone try to confirm...
and please if you confirm double check to be sure isn't your proxy that is changing the data

**Comment by Nerixyz** [comment]
> Is Instagram official app using http 1.1 or http2?

It can use HTTP/3, HTTP/2 and HTTP/1.1. 



> This is an absurd error since http2 specification says that all headers should be lowercase.

The HTTP/2 spec only says the header field names should be encoded as lowercase ([Spec](https://tools.ietf.org/html/rfc7540#section-8.1.2)). It doesn't matter how you write the headers in (most if not all) http/2 clients as the headers are case-insensitive.

 

> Then i tried to use mitmproxy but it didnt work well and the connection went http 1.1

Works fine for me. You might need to proxy in socks5 mode.

> are the response headers named all lowercase or it kept that pattern like:

As for the headers you listed, they are in that pattern (in the apk, maybe proxygen lowercases them). But there's really little to no reason you need to care as comparisons are case-insensitive.

**Comment by itsMoji** [comment]
@Nerixyz Thanks for contributing to this repo!
