### ISSUE TITLE
Decrypt TLSv1.3

### ISSUE THREAD

**Issue by ivanyadeshko** [itsMoji/Instagram_SSL_Pinning#30]
Hi, Moji ;)
I have some problems with decryption trafic. I think that TLSv1.3 and Burb cant decrypt this.

Burp error message: 
Error | Proxy | [39]  The client failed to negotiate an SSL connection to i.instagram.com:443: The client supported protocol versions [TLSv1.3, (D)TLS--5.26] are not accepted by server preferences [TLS12, TLS11, TLS10, SSL30, SSL20Hello]

And i have question. How decrypt trafic now? maby its problem only on windows platform ?

**Comment by Nerixyz** [comment]
The readme explicitly says Burp 1, not Burp 2. This will fix your issue.

**Comment by ivanyadeshko** [comment]
Ok, Testing burp version 1.7.36
Received the next error: 
1572509343789 | Proxy | [30]  The client failed to negotiate an SSL connection to b.i.instagram.com:443: Received fatal alert: unknown_ca
What can i do now ?

**Comment by RMatushkin** [comment]
It seems like you didn't replace the file 'libliger.so'.
The most important action is you should open Instagram app, press the login button, write any username and password to get the error login pop-up. This action uses 'libliger.so' file. And now you should close the app and replace the file.
"Received fatal alert: bad_certificate" message makes it clear that you haven't replaced the file yet and you are not able to catch traffic, MITM doesn't work due to SSL pinning protection.

**Comment by enriquejr99** [comment]
Why must Burp version must be 1.7.36?

**Comment by byehack** [comment]
> * Java version must be >= 11

java 8 also works as well.
