### ISSUE TITLE
sn_nonce sn_result

### ISSUE THREAD

**Issue by codebased421** [itsMoji/Instagram_SSL_Pinning#77]
Can anybody help with the sn_nonce and sn_result params for account creation?

Found with SSL Pinning:
"sn_nonce":"Y29kZWJhc2VkNDIxQGdtYWlsLmNvbXwxNTk3NDIzNjM1fBC1AXcOed9xp6mA0SXu6hhDY6Fk8nJNFw=="

codebased421@gmail.com|1597423635|wyq%CcdrM

email | time | ??

Currently I have the following for the sn_result:

"sn_result" : "GOOGLE_PLAY_UNAVAILABLE:+SERVICE_INVALID"

IG_VERSION = '133.0.0.32.120';

**Comment by itsMoji** [comment]
Many repositories like [github.com/dilame/instagram-private-api](https://github.com/dilame/instagram-private-api/blob/b9d3ef3623f798cc050365b9470cb751341a60c0/src/repositories/account.repository.ts#L161) use an empty value for `sn_nonce`, 

Some use random bytes for the last part of sn_nonce, like [github.com/clicker777/Instagram-clicker777-master](https://github.com/clicker777/Instagram-clicker777-master/blob/21dfc9b771291d4b069cdf9f0960c97539fca99c/src/Request/Account.php#L40) and [github.com/johnriderr/insta_project](https://github.com/johnriderr/insta_project/blob/d5788e656bc7be5c599ca59844aefd395a58e664/work_with_net.py#L69)

**Comment by codebased421** [comment]
Thanks!

**Comment by denizaydemir** [comment]
You cannot create accounts using private api. sn_nonce comes from attestation result(See SafetyNet). You can regenerate sn_nonce, make it valid and directly came from Google API's (Using Instagram's Google API Key) but attestation request should be called from Instagram app itself.

**Comment by progl** [comment]
where I can find Google API key?

**Comment by denizaydemir** [comment]
It could be seen in libstrings.so getScrambler methods returned strings. It was easy to grab with frida, but not that easy anymore I guess. Another try was to get the key while its being sent to attestation API during account creation. Yet it's been a while since the last time I checked the second approach.

**Comment by IvanMMM** [comment]
That's interesting. So you are saying, that is is possible to call Google API and generate valid sn_result if we can grab Google API key?

**Comment by denizaydemir** [comment]
You can generate a legal sn_result via SafetyNetApi using IG's Google API key, when it comes to validity, I think IG makes the desicion there because If you look at the sn_result it is jwt rs256. It contains the attestation caller package name. However I have never tried neither impersonating package name or actually sending that sn_result into account creation endpoint. Those might work, or not.
And a little note, attestation result does not contain the package name of the caller app if the device is rooted because the integrity is not reliable. Also IG actually accepts that result. Why? You can create IG accounts on rooted devices.

**Comment by IvanMMM** [comment]
Is there a chance you can get this Google API key for us? Not for free, ofc :)

**Comment by denizaydemir** [comment]
I have checked some things and the used Google API key is the same as the last time I checked(1 year ago). I have a question in mind, how can I actually show you that that key belongs to IG. I know it is but I'm asking it show you that my claims are not dud.
Let's not discuss anymore on this repo. Any questions to me can be sent to my email: deniz@imp.codes
