### ISSUE TITLE
libliger.so deassembly verify instructions

### ISSUE THREAD

**Issue by denizaydemir** [itsMoji/Instagram_SSL_Pinning#82]
Hello, I have been patching libliger.so using IDA. However, in the newer versions the good old verifyWithMetrics function seems to be changed(not used anymore?). Would you mind sharing the function name you are editing please? Or any little hint will be a huge help.

**Comment by metin02oktay** [comment]
Yes, I need too :)

**Comment by denizaydemir** [comment]
No tips? :(

**Comment by enriquejr99** [comment]
To know which function he patched, install the original Instagram APK on your Android device and open it so that the original libliger.so file is created. Then, compare itsMoji's patched libliger.so file with the original one (same version) using HxD hex editor. Just use Analysis > Data compare > Comparison. Finally, search for the modified hex sequence(s) on IDA to understand what was changed.

On the latest version (v170.2.0.30.474) the verifyWithMetrics function was patched.

**Comment by denizaydemir** [comment]
@enriquejr99 Thanks for the comparison method explanation. That was exactly what I have been trying to achieve. However, I wasn't able to find a good binary comparison tool. Tried with 2 different tools, IDA plugins but no luck. Should have researched and tried more tools, never heard of HxD hex editor.

**Comment by xenud** [comment]
What tool did you use to unpack libs.spk.zst?

**Comment by enriquejr99** [comment]
To unpack open the Instagram app once and it unpacks itself.
