### ISSUE TITLE
How the patching works?

### ISSUE THREAD

**Issue by lucaswxp** [itsMoji/Instagram_SSL_Pinning#91]
Congratulations on the project! I find it very interesting, and would like to learn more.

Can you guys please give me an overral how you managed to patch the binary? What exactly was done to libliger.so? Are there any resources that would be helpful for me to read?

Thanks

**Comment by enriquejr99** [comment]
The patch modifies the `verifyWithMetrics` function in the `libliger.so` file so that it always returns `true`. This function is used by the app to verify whether the SSL certificate is valid or not. To patch the file yourself you can use a disassembler such as Ghidra or IDA Pro.

How to patch:
1. Open `libliger.so` with a disassembler
2. Search for the `verifyWithMetrics` function
3. Produce a control flow graph (CFG) to make your life easier
4. Find which branch is the right one
5. Edit an instruction so that it directly branches to the right branch from start
6. Recompile the file

This looks challenging at first, but it really just takes 15 minutes if you have experience. Note that at the moment, this patch doesn't remove the SSL pinning for the MQTT traffic (See: [#90](https://github.com/itsMoji/Instagram_SSL_Pinning/issues/90)). You may want to have a look at the [ARM instruction](https://developer.arm.com/documentation/dui0068/b/arm-instruction-reference) set.

**Comment by lucaswxp** [comment]
That's very interesting, thanks. I saw a technique using smali to patch the
jar file, how that compares to the tools you mentiones? Are they equivalent?

Em ter, 2 de mar de 2021 2:39 PM, Enrique Jorge <notifications@github.com>
escreveu:

**Comment by enriquejr99** [comment]
I am not aware of such technique, do you have a link to it? However, the certificate verification happens on the shared object `libliger.so`, so I'm **guessing** the technique you mention is likely patching the [native](https://en.wikipedia.org/wiki/Java_Native_Interface) call to the `verifyWithMetrics` function, hence they will not need a disassembler for that but a decompiler such as [jadx](https://github.com/skylot/jadx) to locate the native call.

**Comment by lucaswxp** [comment]
Here it is  https://link.medium.com/bMU90LKwjeb

I wonder how they trace it down to the *verifyWithMetrics* function in the
shared library.

Em ter, 2 de mar de 2021 10:51 PM, Enrique Jorge <notifications@github.com>
escreveu:

**Comment by enriquejr99** [comment]
Both examples in the [link](https://link.medium.com/bMU90LKwjeb) are very specific and I doubt they would work with Instagram, but their approach is similar to what I mentioned above using a decompiler. The thing is, Instagram implemented their SSL pinning mechanism (at least for the HTTP traffic) in C/C++, not in Java as those 2 examples did. This is because Facebook has many well-maintained HTTP libraries written in C/C++; some examples are: [proxygen](https://github.com/facebook/proxygen), [fizz](https://github.com/facebookincubator/fizz) and [folly](https://github.com/facebook/folly).

The way they traced it down to `verifyWithMetrics` was by searching for the error string the application throwed when it detected an invalid certificate.

**Comment by lucaswxp** [comment]
Ohhh, that makes so much sense. Thanks again Enrique ;)

Em ter, 2 de mar de 2021 11:48 PM, Enrique Jorge <notifications@github.com>
escreveu:
